### ISSUE TITLE
Change default marker used for 3-d scatter

### ISSUE THREAD

**Issue by astrofrog** [glue-viz/glue-jupyter#144]
The default marker used for the 3d scatter (ipyvolume) viewer is currently 'sphere', which is the slowest. We should change this to 'box' (and make sure it is indeed faster).

**Comment by astrofrog** [comment]
@jsub1 - would you be happy to look into this? It should be a very easy fix.

**Comment by maartenbreddels** [comment]
What about circle_2d? It has less 3d effect, but should be faster.

(from mobile phone)

**Comment by astrofrog** [comment]
I haven't tried, but that sounds promising - it would be similar to what we do in the Qt interface

**Comment by jsub1** [comment]
The diamond marker renders faster than either the box or circle_2d (23.66 fps with 1.5M points vs 18.02 or 14.81). We should default to the diamond unless there are aesthetic reasons not to.

**Comment by astrofrog** [comment]
Sounds good to me!

**Comment by maartenbreddels** [comment]
Can I ask how you measured the FPS?

**Comment by astrofrog** [comment]
I'll close this but I'd be interested in also knowing how the FPS was measured!

**Comment by jsub1** [comment]
Sorry about the delay in answering this. 

What I did was to create a small looping animation using the movie maker. I then used the performance section of the developers tool and recorded multiple loops of the short animation.

 The numbers quoted come from Firefox, because that performance tool will just display the average, min and max FPSs unlike Chrome. The numbers above are average.
