### ISSUE TITLE
API change: Make "data" the first keyword argument

### ISSUE THREAD

**Issue by pllim** [glue-viz/glue-jupyter#73]
For example, I loaded a cube or image from your `data = app.load_data(filename)` method. Then intuitively (and given the lack of API doc on RTD), I tried:

```python
app.imshow(data)
```

or

```python
app.volshow(data)
```

However, doing that, I got a traceback. It turns out that currently I needed to provide `data=data` explicitly, which I find non-intuitive.

xref spacetelescope/dat_pyinthesky#28

**Comment by astrofrog** [comment]
I agree that ``data`` should always be the first argument since that's likely to be the most common use case.

**Comment by astrofrog** [comment]
So looking into this a bit more, I think this may have been originally motivated by @eteq's proposed API, where if there is only one dataset, then the dataset doesn't need to be specified. I wonder whether the best solution would be to just make all arguments keyword-only so that no assumptions are made about what the 'first' argument is. Note that this still allows users to now specify any arguments if they just want the default (e.g. the only dataset, and default attributes).

**Comment by pllim** [comment]
> if there is only one dataset, then the dataset doesn't need to be specified

Not sure if I 100% onboard here. Explicit is better than implicit? Anyways, if that is the way you want to go, then keyword-only would be the next best thing, yes.

**Comment by astrofrog** [comment]
We now use keyword-only arguments, so closing this!
